# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-14 12:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agenda', '0005_auto_20170624_2135'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(blank=True, max_length=13)),
                ('idUfsc', models.CharField(blank=True, max_length=50)),
                ('setor', models.CharField(blank=True, max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='reservaequipamento',
            name='estado',
            field=models.CharField(choices=[(b'A', b'Aprovado'), (b'D', b'Desaprovado'), (b'E', b'Esperando')], default=b'E', max_length=1),
        ),
        migrations.AlterField(
            model_name='reservaespacofisico',
            name='estado',
            field=models.CharField(choices=[(b'A', b'Aprovado'), (b'D', b'Desaprovado'), (b'E', b'Esperando')], default=b'E', max_length=1),
        ),
    ]
